### ISSUE TITLE
Improve intro slides

### ISSUE THREAD

**Issue by gcroci2** [carpentries-incubator/gen-ai-coding#21]
- Update the slides in order to say less about Command, Chat, Autocomplete in the intro. Maybe remove part 2 slide
- Move context awarness slide to the introduction 
- Highlight differences and common features among main tools, keep the table and the comparison, but slightly less detail
- Besides the areas of application, we got a comment about adding a framework/map/visualization to understand the capabilities of AI coder from small-scale tasks to large-scale tasks to their future capabilities. 
- About the slide of “area of application”: one more item can be added: explaining errors/bugs

**Comment by olgaminaeva** [comment]
I updated the slides but I'm not sure about the comment about adding a framework/map/visualization to understand the capabilities of AI coder from small-scale tasks to large-scale tasks to their future capabilities. I made a slide but I don't like it that much, so I'm considering skipping it. I don't think it has a big added value
