### ISSUE TITLE
Improve episode 1 lesson

### ISSUE THREAD

**Issue by gcroci2** [carpentries-incubator/gen-ai-coding#24]
- Add ref to https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev, and multiline functionality about the last Copilot version. Maybe these can go under a section that needs to be checked and updated before every lesson (changes happen very fast). 
   - Specify the need of update also when mentioning other tools. "Maybe create a perpetual issue for that". 
- Update slides if needed

**Comment by gcroci2** [comment]
I wrote here "episode 2", but I think that this stuff should be actually added to episode 1, in the part when other tools are described. I changed the title and assigned you to it @olgaminaeva

**Comment by olgaminaeva** [comment]
Sorry, I'm not sure what I need to do with this link. Add it as a new tool in the table? Or add something like a spoiler or callout that the tool overview should be updated?

**Comment by gcroci2** [comment]
Up to you :) 

I'd say:

> * Add ref to https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev

This could be a new tool in the table

> and multiline functionality about the last Copilot version

This could be a callout

> Maybe these can go under a section that needs to be checked and updated before every lesson (changes happen very fast).

I think this applies to all the tools and features mentioned in episode 1, so you can create an issue titled something like "Check and update tools and features", that can stay always open and act as a checklist before teaching the workshop

@olgaminaeva
