### ISSUE TITLE
Improve episode 3 slides

### ISSUE THREAD

**Issue by gcroci2** [carpentries-incubator/gen-ai-coding#26]
- In text heavy slides/slides with many bullet points: animate the points in, rather than showing everything at once, or split the bullet points into separate slides (e.g. security measures slide) (+1) 
- You may need to give researchers examples of ‘sensitive situations.’ I suspect these are not apparent to them always 
- When discussing regulations, etc. Stick to what is relevant for your audience. Things like what law enforcement is/isnt allowed is not really that important here, whereas what is/isnt allowed in (medical) research is. 
- Do the exercise earlier in this module, before discussing all the potential issues, and use the things people came up with to introduce these issues.

**Comment by olgaminaeva** [comment]
I'm slightly confused by the comment about giving researchers examples of ‘sensitive situations.’ Is this about the first point, where we ask to list at least two potential risks or vulnerabilities that could arise from using an AI coding assistant in this project? And the general assignment specifies a new project involving sensitive user data, which seems pretty clear to me. What part should I clarify @gcroci2?

**Comment by gcroci2** [comment]
> I'm slightly confused by the comment about giving researchers examples of ‘sensitive situations.’ Is this about the first point, where we ask to list at least two potential risks or vulnerabilities that could arise from using an AI coding assistant in this project? And the general assignment specifies a new project involving sensitive user data, which seems pretty clear to me. What part should I clarify @gcroci2?

I guess the comment about sensitive situations refers to explicitly listing a few examples to make it very clear when a situation is considered "sensitive" in this context. It can be just a couple of bullet points during the explanation (reiterating eventual examples covered by the exercise), both in the episode and the slides @olgaminaeva
