### ISSUE TITLE
Add lesson to carpentries incubator

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/gen-ai-coding#27]
I was at CarpentryConnect and was confronted with the fact that many people are working on the same lesson material without knowing about each others efforts.

To make this lesson more findable I suggest to add it to the carpentries incubator, you can [open a proposal issue](https://github.com/carpentries-incubator/proposals/issues) in 5 minutes. I could also do it for you if you want. Just to remind you that the incubator is ment to **incubate** lessons, your lesson does not need to be finished in any way and even lesson ideas are good to add to the incubator.

You can also post a message in the carpentries slack to mention that you are working on this lesson. Which I can also do for you if you want.

**Comment by gcroci2** [comment]
I can also open a proposal issue. I am only wondering @svenvanderburg, how does the lesson development work then? Do we keep adding improvements here, on Olga's repository, or do we add all the upgrades on the incubator (I think the latter would be better)?

**Comment by svenvanderburg** [comment]
The repository will be migrated to the carpentries-incubator group. All lesson development will happen there.

**Comment by gcroci2** [comment]
I opened a new issue as instructed [here](https://github.com/carpentries-incubator/proposals/issues/203)
